### ISSUE TITLE
Team logos are showing links rather than the logos for tables

### ISSUE THREAD

**Issue by willphill9** [andreweatherman/cbbplotR#2]
# Install the necessary packages (if not already installed)
if (!require("pak")) install.packages("pak")
pak::pak("andreweatherman/cbbplotR")
pak::pak("andreweatherman/cbbdata")

# Load the libraries
library(cbbplotR)
library(cbbdata)
library(gt)
library(tidyverse)

# Fetch ACC team data for 2025 season using the cbbdata package
acc_team_data_2025 <- cbd_torvik_ratings(year = 2025, conf = 'ACC')

# Select only the relevant columns: adjusted offense, adjusted defense, and barthag
acc_team_data_2025 <- acc_team_data_2025 %>%
  select(team, adj_o, adj_d, barthag) %>%
  arrange(desc(barthag))  # Rank teams by barthag

# Use the gt_cbb_teams function to embed logos into the gt table
acc_team_data_2025 %>%
  gt_cbb_teams(team) %>%  # Add team logos directly using cbbplotR's utility
  gt() %>%
  cols_label(
    team = "Team",
    adj_o = "Adj Offense",
    adj_d = "Adj Defense",
    barthag = "Barthag"
  ) %>%
  tab_header(
    title = md("**ACC Torvik Projections for 2025**"),
    subtitle = "Ranked by Barthag"
  ) %>%
  fmt_number(columns = c(adj_o, adj_d, barthag), decimals = 2) %>%
  tab_options(
    table.font.size = "medium"
  )

**Comment by andreweatherman** [comment]
`gt_cbb_teams` provides HTML code that needs to be rendered with `fmt_markdown(team)`
